#
# docker-compose.yml for the example-webservice project
#
version: '3'
services:
  webservice:
    image: mwngsm/example-project:dev-latest
    ports:
     - "7676:7676"
    environment:
      - RUNTIME_STAGE=dev
      - LOG_LEVEL=DEBUG

      - LISTENING_PORT=7676
      - SERVER_CERT_FILE="foo"
      - SERVER_KEY_FILE="foo"

      - MYSQL_HOST="localhost"
      - MYSQL_PORT="3333"
      - MYSQL_USER="test_user"
      - MYSQL_PW="testpw"
      - MYSQL_DB_NAME="exampledb"
      - DB_CLIENT="MOCK"

    deploy:
      restart_policy:
        condition: any
        delay: 1s
